### ISSUE TITLE
package-lock.json causing npm install to fail (with along list of problems/errors)

### ISSUE THREAD

**Issue by jurajofsweden** [material-components/material-components-web-codelabs#100]
The "2. Set up your development environment" in mdc-101 and mdc-102 fail at the step "npm install" with a long list of problems/errors. After deleting the package-lock.json the "npm install" runs smoothly. Please remove the package-lock.json from the git repo or update the instructions to remove the package-lock.json before running npm install.

**Comment by abhiomkar** [comment]
Thanks for the tip!

This is likely a dup of #125
