### ISSUE TITLE
[codelab] <Change title>

### ISSUE THREAD

**Issue by cynthiasunrise** [material-components/material-components-web-codelabs#113]
The "t" prefix alters the order of the codelabs...

Pls remove it from here:
tMDC-103 Web: Material Theming with Color, Shape, Elevation and Type (Web)

**Comment by MewX** [comment]
LOL, that was a misedit from someone. A fix should be published soon.

**Comment by abhiomkar** [comment]
Thanks for spotting it. Docs are now edited, will take few minutes to publish.

**Comment by MewX** [comment]
@abhiomkar 

I don't think `golink/mdc-103-web` has been updated
