### ISSUE TITLE
[codelab] @use is coming soon, but it's not supported in this version of Dart Sass.

### ISSUE THREAD

**Issue by ajith007** [material-components/material-components-web-codelabs#116]
Followed the instructions exactly as in the lab, noticed the error on the console and as a result the fields are not displayed correctly .. 
https://codelabs.developers.google.com/codelabs/mdc-101-web/#2
![image](https://user-images.githubusercontent.com/1762945/75097867-319b0900-5575-11ea-81be-e24a4e5bcabe.png)

any step missing in the lab? kindly assist.

**Comment by lmbell89** [comment]
Edit the package.json file and change the dart sass version number 
"dart-sass": "^1.25.0"
Then run npm install

**Comment by ajith007** [comment]
Thanks @lmbell89 ! That did the trick! :)
![image](https://user-images.githubusercontent.com/1762945/75820429-f2816a80-5d61-11ea-8123-336fa69f6e1b.png)
