### ISSUE TITLE
 MDC-102 Web: Material Structure and Layout (Web) Too many issues in the codelab

### ISSUE THREAD

**Issue by vasisht24** [material-components/material-components-web-codelabs#121]
This codelab tutorial has not been properly updated! Please updated the proper working and steps required to learn MDC. We are falling into many compile errors

 
ERROR in ./home.js
    Module not found: Error: Can't resolve '@material/list' in 'C:\Users\Desktop\mdc\material-components-web-codelabs-master\mdc-102\starter'       
     @ ./home.js 3:12-37
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./home.js

**Comment by freiit** [comment]
#122 should fix this.

**Comment by AjithPG** [comment]
Same here. I got some errors while building.
 ERROR in ./home.scss
    Module build failed:
    undefined
    ^
          @use is coming soon, but it's not supported in this version of Dart Sass.
       ╷
    23 │ @use "./common";
       │ ^^^^^^^^^^^^^^^
       ╵
      node_modules\@material\drawer\mdc-drawer.scss 23:1  root stylesheet
      stdin 2:9                                           root stylesheet
          in C:\Users\AJITH PG\Downloads\material-components-web-codelabs-master\material-components-web-codelabs-master\mdc-102\starter\node_modules\@material\drawer\mdc-drawer.scss (line 23, column 1)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./home.scss
