### ISSUE TITLE
material select in mdc-111 is not working

### ISSUE THREAD

**Issue by vidur-ui** [material-components/material-components-web-codelabs#128]
I think usage of material select in mdc-111 is not correct as they have used option element in it, but according to (https://material.io/develop/web/components/input-controls/select-menus/) we should use material list instead of option .

Using option tag and mdc-select we get the mixture of both which is weird

![image](https://user-images.githubusercontent.com/56824234/78897225-74fef780-7a8f-11ea-92df-04280e0ac3fc.png)

I hope I'm right, do correct me if I'm wrong

**Comment by wamalwa** [comment]
> 
> 
> I think usage of material select in mdc-111 is not correct as they have used option element in it, but according to (https://material.io/develop/web/components/input-controls/select-menus/) we should use material list instead of option .
> 
> Using option tag and mdc-select we get the mixture of both which is weird
> 
> ![image](https://user-images.githubusercontent.com/56824234/78897225-74fef780-7a8f-11ea-92df-04280e0ac3fc.png)
> 
> I hope I'm right, do correct me if I'm wrong

I ran into the same issue. I even tried to compile the code in the **complete** folder but still returned the same result.

**Comment by colebennington** [comment]
I have the same issue as well. I had it when building from start and compiling the complete.

**Comment by abhiomkar** [comment]
Please [see docs](https://github.com/material-components/material-components-web/blob/v6.0.0/packages/mdc-select/README.md) of MDC Web v6.0.0 for latest guidance on how to use select menus (Including updated HTML structure).

Codelabs are not updated for v6.0.0, follow [this bug](https://github.com/material-components/material-components-web-codelabs/issues/135) for tracking.
