### ISSUE TITLE
textfield issue in mdc-111

### ISSUE THREAD

**Issue by vidur-ui** [material-components/material-components-web-codelabs#129]
Due to some reason I'm facing an issue in mdc-111 in the textfield component which is that only first text-field is applying the styles of the textfield component and floating label and other textfield of the forms are not.
don't know why
if anyone can help

below are the screenshots:

![image](https://user-images.githubusercontent.com/56824234/79269477-251e9700-7eba-11ea-8047-b67a0e3d006f.png)

![image](https://user-images.githubusercontent.com/56824234/79269543-42536580-7eba-11ea-9755-a7ff93ebcb73.png)

**Comment by abhiomkar** [comment]
Can you share your HTML markup and MDC Web version that you're using to investigate?

Here is the latest full demo on Glitch that renders Text Field https://glitch.com/edit/#!/new-web

**Comment by abhiomkar** [comment]
Please follow [docs from material.io](https://material.io/develop/web/components/input-controls/text-field/) for up-to date documentation on latest HTML structure for text field.

Codelabs will be updated to v6 in #135
