### ISSUE TITLE
Can't start with MDC-101

### ISSUE THREAD

**Issue by Ashvith** [material-components/material-components-web-codelabs#131]
Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Ashvith Shetty>cd C:\material-components-web-codelabs-master\mdc-101\starter

C:\material-components-web-codelabs-master\mdc-101\starter>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 10479 packages in 3.894s
found 573 vulnerabilities (316 low, 2 moderate, 255 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\material-components-web-codelabs-master\mdc-101\starter>npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ dart-sass@1.25.0
+ webpack-dev-server@2.11.5
added 23 packages from 16 contributors, removed 40 packages and updated 72 packages in 13.876s

19 packages are looking for funding
  run `npm fund` for details

fixed 563 of 573 vulnerabilities in 10479 scanned packages
  6 vulnerabilities required manual review and could not be updated
  3 package updates for 4 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

C:\material-components-web-codelabs-master\mdc-101\starter>

**Comment by Ashvith** [comment]
[2020-04-21T10_02_09_540Z-debug.log](https://github.com/material-components/material-components-web-codelabs/files/4509190/2020-04-21T10_02_09_540Z-debug.log)

**Comment by abhiomkar** [comment]
Dup of #125
