### ISSUE TITLE
Issue with new @material/textfield package [codelab] <PLACE YOUR ISSUE TITLE HERE>

### ISSUE THREAD

**Issue by supriodutta** [material-components/material-components-web-codelabs#134]
I followed all the steps but the output was not as expected. After checking the complete project code, I found that the issue is with the version.

If I am using -
  "dependencies": {
    "@material/ripple": "^4.0.0",
    "@material/textfield": "^4.0.0"
  }
then everything is working fine. But while I was installing these packages using npm, it was giving issue. New version which is 6.0.0 ("@material/textfield": "^6.0.0") is having some issue. It is giving below error while starting -

ERROR in ./login.scss
    Module build failed: 
    @use "./mixins";
    ^
          @use is coming soon, but it's not supported in this version of Dart Sass.
       ╷
    23 │ @use "./mixins";
       │ ^^^^^^^^^^^^^^^
       ╵
      node_modules/@material/textfield/mdc-text-field.scss 23:1  root stylesheet
      stdin 2:9                                                  root stylesheet
          in /Users/supriodutta/MyFiles/SuprioFiles/ML/Practice/test_jaya/Time_Conversion_Utility/node_modules/@material/textfield/mdc-text-field.scss (line 23, column 1)
     @ multi (webpack)-dev-server/client?http://localhost:8081 ./login.scss
<img width="1680" alt="Screenshot 2020-04-28 at 6 45 44 AM" src="https://user-images.githubusercontent.com/19893410/80436079-e5c16300-891b-11ea-80ff-adbcb1b1dafc.png">

**Comment by abhiomkar** [comment]
Please upgrade to latest Sass version to use latest Dart Sass syntax that supports `@use` rule.

If you're following [MDC-101-web](https://codelabs.developers.google.com/codelabs/mdc-101-web/#3) codelab which suggests `@import` syntax existing version of Sass should still work. You should be able to still use `@import` with either `v4` or `v6` of MDC Web.

Please follow [getting started](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) guide for full setup instructions.

We'll update our codelabs to latest version of MDC Web (v6.0.0), please [follow this bug](https://github.com/material-components/material-components-web-codelabs/issues/135) for updates.
