### ISSUE TITLE
An exercise in futility

### ISSUE THREAD

**Issue by RudieKat** [material-components/material-components-web-codelabs#210]
Dear developers and even more so - dear product manager of material.io:

Are you joking? Is this an elaborate prank? Why are you pushing an io-framework using old versions of components, ancient at this point versions of frameworks and with instructions that are downright WRONG.

The issue here isn't that there is ONE issue. It's that you are not taking the responsibility for the product and showing that software governance is not a core focus or even a consideration. Do you think this reflects well on other Google cross-platform products? Go? (Mutex still broken? Cool. Maybe at some point you even get around to.... you know. Documenting stuff.) Fluttter? So incomplete it's not even  worth mentioning. 

While I am sure this attempt at shaking some sort of sense into you will soon be > /dev/null  let me reassure you. I can't, as a CTO, trust that a company that does this actually can manage much of everything long term. Maintenance is boring? Sure. Cool.

Then kindly stop releasing products and focus on your core business: selling ads based on tracking information.

**Comment by asyncliz** [comment]
Thank you for your concerns, and I'm sorry you are frustrated.

I'd encourage issues filed here to focus on specific problems with the Material web codelabs repository so that our team can prioritize and address it.

Thanks!
