### ISSUE TITLE
[codelab] MDC-103 Web: Divider color

### ISSUE THREAD

**Issue by ajinkyarao** [material-components/material-components-web-codelabs#23]
In step 4 of the MDC-103 Web codelab, the instructions say to set the color of the divider explicitly to `#EAA4A4`, but in step 7, the instructions do not explicitly say to remove that property. Step 7 only says to `include` the `mdc-theme-prop`, which has no effect if the background color is still being set.

If this is intentional, my apologies.
I really enjoyed working on this. 🙂

**Comment by williamernest** [comment]
@ajinkyarao Thanks for filing this issue. I've updated the codelab prose to be more explicit about replacing the previous property with the mixin.
