### ISSUE TITLE
(MDC 111) Text Fields collapse into a horizontal line when screen is resized

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-web-codelabs#24]
MDC-111-Web
Step 4

Actual behavior:
When you resize the screen displaying the text fields they collapse into a single overlapping horizontal line.

Expected behavior:
Resizing the screen will still allow the text fields to be visible.

**Comment by lynnjepsen** [comment]
@ianegordon can you attach a screenshot. Im not sure I understand why we want the text fields to collapse into a single overlapping horizontal line?

**Comment by kfranqueiro** [comment]
@lynnjepsen I'm pretty sure you're describing the bug, not the desired behavior. I think the point is they want the fields to wrap as needed to fit the screen. However, I wasn't able to repro this within the `complete` code, so I'm wondering if this is something only reproducible after replacing one type of input element in the codelab but not the other.

**Comment by kfranqueiro** [comment]
I ran through MDC-111 through the end of Step 4 and couldn't repro this, even when intentionally trying to make mistakes that might lead to something of this nature. I talked with Ian and showed him a couple of things, but as far as we can tell this is not something reproducible by following the codelab's directions, so I'm closing this issue.
