### ISSUE TITLE
Webpack not compiling

### ISSUE THREAD

**Issue by istudiomobile** [material-components/material-components-web-codelabs#25]
On step 3 when adding the fields receive this error in console "Module build failed: Error: Couldn't find preset "es2015" relative to directory"

Googled it and apparently is something related to the version of babel not playing nicely with other dependencies, any ideas how to resolve?

Thank you in advance.

**Comment by kfranqueiro** [comment]
Sorry to hear you encountered this issue. Would you be able to tell us what version of node and npm you're using, and the output of `npm ls --depth 1` in the directory you're running the codelab in (e.g. mdc-101/starter)?

**Comment by istudiomobile** [comment]
/Users/iSTUDIOMobile/Documents/Sandbox/material-components-web-codelabs
├─┬ @material/textfield@0.35.1
│ ├── @material/animation@0.34.0
│ ├── @material/base@0.35.0
│ ├── @material/floating-label@0.35.0
│ ├── @material/line-ripple@0.35.0
│ ├── @material/notched-outline@0.35.0
│ ├── @material/ripple@0.35.0
│ ├── @material/rtl@0.35.0
│ ├── @material/theme@0.35.0
│ └── @material/typography@0.35.0
└─┬ babel-preset-env@1.7.0
  ├── babel-plugin-check-es2015-constants@6.22.0
  ├── babel-plugin-syntax-trailing-function-commas@6.22.0
  ├── babel-plugin-transform-async-to-generator@6.24.1
  ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
  ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
  ├── babel-plugin-transform-es2015-block-scoping@6.26.0
  ├── babel-plugin-transform-es2015-classes@6.24.1
  ├── babel-plugin-transform-es2015-computed-properties@6.24.1
  ├── babel-plugin-transform-es2015-destructuring@6.23.0
  ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1
  ├── babel-plugin-transform-es2015-for-of@6.23.0
  ├── babel-plugin-transform-es2015-function-name@6.24.1
  ├── babel-plugin-transform-es2015-literals@6.22.0
  ├── babel-plugin-transform-es2015-modules-amd@6.24.1
  ├── babel-plugin-transform-es2015-modules-commonjs@6.26.2
  ├── babel-plugin-transform-es2015-modules-systemjs@6.24.1
  ├── babel-plugin-transform-es2015-modules-umd@6.24.1
  ├── babel-plugin-transform-es2015-object-super@6.24.1
  ├── babel-plugin-transform-es2015-parameters@6.24.1
  ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1
  ├── babel-plugin-transform-es2015-spread@6.22.0
  ├── babel-plugin-transform-es2015-sticky-regex@6.24.1
  ├── babel-plugin-transform-es2015-template-literals@6.22.0
  ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
  ├── babel-plugin-transform-es2015-unicode-regex@6.24.1
  ├── babel-plugin-transform-exponentiation-operator@6.24.1
  ├── babel-plugin-transform-regenerator@6.26.0
  ├── browserslist@3.2.7
  ├── invariant@2.2.4
  └── semver@5.5.0

this is the output of of npm ls --depth 1, using nvm with node version 9.10.1

**Comment by kfranqueiro** [comment]
I'm a bit confused in that the above output looks like it only includes what you installed manually... it should include a bunch of other stuff installed via `npm install`.

However, I also noticed that the top line of the output seems to indicate `material-components-web-codelabs` as the working directory, not `mdc-101/starter`? Can you retry the codelab from the beginning and ensure that you're running `npm` commands within the `starter` directory?

Here's what my `npm ls --depth 1` output looks like after running `npm install` under `mdc-101/starter`, using the latest Node 9 via nvm to try to get as close to your environment as possible:

```
mdc-101-web@0.0.0 /Users/kfranqueiro/dev/codelabs/mdc-101/starter
├─┬ babel-core@6.26.3
│ ├── babel-code-frame@6.26.0
│ ├── babel-generator@6.26.1
│ ├── babel-helpers@6.24.1
│ ├── babel-messages@6.23.0
│ ├── babel-register@6.26.0
│ ├── babel-runtime@6.26.0
│ ├── babel-template@6.26.0
│ ├── babel-traverse@6.26.0
│ ├── babel-types@6.26.0
│ ├── babylon@6.18.0
│ ├── convert-source-map@1.5.1
│ ├── debug@2.6.9
│ ├── json5@0.5.1
│ ├── lodash@4.17.10
│ ├── minimatch@3.0.4
│ ├── path-is-absolute@1.0.1
│ ├── private@0.1.8
│ ├── slash@1.0.0
│ └── source-map@0.5.7
├─┬ babel-loader@7.1.4
│ ├── find-cache-dir@1.0.0
│ ├── loader-utils@1.1.0
│ └── mkdirp@0.5.1
├─┬ babel-preset-es2015@6.24.1
│ ├── babel-plugin-check-es2015-constants@6.22.0
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoping@6.26.0
│ ├── babel-plugin-transform-es2015-classes@6.24.1
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1
│ ├── babel-plugin-transform-es2015-for-of@6.23.0
│ ├── babel-plugin-transform-es2015-function-name@6.24.1
│ ├── babel-plugin-transform-es2015-literals@6.22.0
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.1
│ ├── babel-plugin-transform-es2015-modules-commonjs@6.26.2
│ ├── babel-plugin-transform-es2015-modules-systemjs@6.24.1
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.1
│ ├── babel-plugin-transform-es2015-object-super@6.24.1
│ ├── babel-plugin-transform-es2015-parameters@6.24.1
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1
│ ├── babel-plugin-transform-es2015-spread@6.22.0
│ ├── babel-plugin-transform-es2015-sticky-regex@6.24.1
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
│ ├── babel-plugin-transform-es2015-unicode-regex@6.24.1
│ └── babel-plugin-transform-regenerator@6.26.0
├─┬ css-loader@0.28.11
│ ├── babel-code-frame@6.26.0 deduped
│ ├── css-selector-tokenizer@0.7.0
│ ├── cssnano@3.10.0
│ ├── icss-utils@2.1.0
│ ├── loader-utils@1.1.0 deduped
│ ├── lodash.camelcase@4.3.0
│ ├── object-assign@4.1.1
│ ├── postcss@5.2.18
│ ├── postcss-modules-extract-imports@1.2.0
│ ├── postcss-modules-local-by-default@1.2.0
│ ├── postcss-modules-scope@1.1.0
│ ├── postcss-modules-values@1.3.0
│ ├── postcss-value-parser@3.3.0
│ └── source-list-map@2.0.0
├─┬ extract-loader@1.0.2
│ └── loader-utils@1.1.0 deduped
├─┬ file-loader@1.1.11
│ ├── loader-utils@1.1.0 deduped
│ └── schema-utils@0.4.5
├─┬ node-sass@4.9.0
│ ├── async-foreach@0.1.3
│ ├── chalk@1.1.3
│ ├── cross-spawn@3.0.1
│ ├── gaze@1.1.2
│ ├── get-stdin@4.0.1
│ ├── glob@7.1.2
│ ├── in-publish@2.0.0
│ ├── lodash.assign@4.2.0
│ ├── lodash.clonedeep@4.5.0
│ ├── lodash.mergewith@4.6.1
│ ├── meow@3.7.0
│ ├── mkdirp@0.5.1 deduped
│ ├── nan@2.10.0
│ ├── node-gyp@3.6.2
│ ├── npmlog@4.1.2
│ ├── request@2.79.0
│ ├── sass-graph@2.2.4
│ ├── stdout-stream@1.4.0
│ └── true-case-path@1.0.2
├─┬ sass-loader@6.0.7
│ ├── clone-deep@2.0.2
│ ├── loader-utils@1.1.0 deduped
│ ├── lodash.tail@4.1.1
│ ├── neo-async@2.5.1
│ └── pify@3.0.0
├─┬ webpack@3.12.0
│ ├── acorn@5.5.3
│ ├── acorn-dynamic-import@2.0.2
│ ├── ajv@6.5.0
│ ├── ajv-keywords@3.2.0
│ ├── async@2.6.0
│ ├── enhanced-resolve@3.4.1
│ ├── escope@3.6.0
│ ├── interpret@1.1.0
│ ├── json-loader@0.5.7
│ ├── json5@0.5.1 deduped
│ ├── loader-runner@2.3.0
│ ├── loader-utils@1.1.0 deduped
│ ├── memory-fs@0.4.1
│ ├── mkdirp@0.5.1 deduped
│ ├── node-libs-browser@2.1.0
│ ├── source-map@0.5.7 deduped
│ ├── supports-color@4.5.0
│ ├── tapable@0.2.8
│ ├── uglifyjs-webpack-plugin@0.4.6
│ ├── watchpack@1.6.0
│ ├── webpack-sources@1.1.0
│ └── yargs@8.0.2
└─┬ webpack-dev-server@2.11.2
  ├── ansi-html@0.0.7
  ├── array-includes@3.0.3
  ├── bonjour@3.5.0
  ├── chokidar@2.0.3
  ├── compression@1.7.2
  ├── connect-history-api-fallback@1.5.0
  ├── debug@3.1.0
  ├── del@3.0.0
  ├── express@4.16.3
  ├── html-entities@1.2.1
  ├── http-proxy-middleware@0.17.4
  ├── import-local@1.0.0
  ├── internal-ip@1.2.0
  ├── ip@1.1.5
  ├── killable@1.0.0
  ├── loglevel@1.6.1
  ├── opn@5.3.0
  ├── portfinder@1.0.13
  ├── selfsigned@1.10.3
  ├── serve-index@1.9.1
  ├── sockjs@0.3.19
  ├── sockjs-client@1.1.4
  ├── spdy@3.4.7
  ├── strip-ansi@3.0.1
  ├── supports-color@5.4.0
  ├── webpack-dev-middleware@1.12.2
  └── yargs@6.6.0
```

You can see that `babel-preset-2015` is among the installed dependencies, since it's listed in mdc-101/starter's package.json.

**Comment by kfranqueiro** [comment]
Since we haven't been able to reproduce this, and haven't heard anything back, I'm going to close this. If you continue to have this issue, I'd suggest starting clean by re-extracting the source from this repo, then retrying the codelab's steps within the `starter` subfolder.
