### ISSUE TITLE
[codelab] <Typo in first paragraph>

### ISSUE THREAD

**Issue by nobillygreen** [material-components/material-components-web-codelabs#27]
"Created by a team of engineers and UX designers at Google, MDC features dozens beautiful and functional UI components"

should instead read as:

"Created by a team of engineers and UX designers at Google, MDC features dozens **of** beautiful and functional UI components"

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. I've fixed the typo and we're working on rolling out updates to the affected codelabs, since the same intro paragraph is used across many of them.
