### ISSUE TITLE
Can't download node-sass on npm install, returns 404 not found

### ISSUE THREAD

**Issue by kevintresuelo** [material-components/material-components-web-codelabs#28]
Whenever I try to run npm install, it processes for a while and then gives me this error:

```
> node-sass@4.8.3 install C:\...\material-components-web-codelabs-master\mdc-103\starter\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-64_binding.node":

HTTP error 404 Not Found
```

**Comment by kfranqueiro** [comment]
I originally couldn't repro this on node 8, but then upgraded to node 10 and could repro the issue. It looks like node-sass added proper node 10 support in 4.9.0. I'll work on a commit to update our package-lock files.

Thanks for reporting, and sorry for the trouble!
