### ISSUE TITLE
[codelab] 404 error for favicon URL in mdc-101 starter

### ISSUE THREAD

**Issue by thiagovilla** [material-components/material-components-web-codelabs#33]
These URLs return a 404 error:
`https://material.io/static/images/simple-lp/favicons/components-192x192.png
https://material.io/static/images/simple-lp/favicons/components-72x72.png`

**Comment by kfranqueiro** [comment]
Thanks for pointing this out.

We should probably update to use `https://material.io/favicon.ico`.
