### ISSUE TITLE
Virus Detected?? material-components/material-components-web-codelabs/archive/master.zip

### ISSUE THREAD

**Issue by emveee** [material-components/material-components-web-codelabs#34]
I am trying to download starter codelab app from material-components/material-components-web-codelabs/archive/master.zip linked from here:

https://codelabs.developers.google.com/codelabs/mdc-101-web/#1

Windows Defender is detecting this as a Virus though: Trojan:Win32/Sprisky.U!cl

Is this a known false positive??

**Comment by kfranqueiro** [comment]
I think that's a false positive... VirusTotal shows it clean everywhere: https://www.virustotal.com/#/file/b783033fa6da400074ba21db86b9700645fa9a7c0a1e802ee2b7f88f77823a12/detection

It seems like zips of other github repositories have been similarly flagged as a false positive for that same trojan. If it's possible to report a false positive to MS, that's the most that can be done.
