### ISSUE TITLE
[codelab] <Mouse hover issue over MDC-101 Web page>

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web-codelabs#38]
When I have my mouse hovered over any part of the MDC-101 Web page for more than 2 seconds, I get a tool tip saying "MDC-101 Web: Material Components (MDC) Basics (Web)" that then follows me around the entire page whenever I stop moving my mouse. Its not to big of an issue, but it is kind of annoying.

Thanks

**Comment by kfranqueiro** [comment]
I've noticed this too... This is unfortunately an issue central to all codelabs due to their use of the `title` attribute on one of their custom elements, which browsers still interpret as tooltip text. This issue has been reported with the codelabs project.
