### ISSUE TITLE
npm installing packages (Babel es2015 and audit)

### ISSUE THREAD

**Issue by nsnikolaev** [material-components/material-components-web-codelabs#39]
I Can't start webpack dev server.
But if I use '**npm install --no-audit**' and when i add in package.json in 'devDependencies' package '**babel-preset-es2015**', then webpack dev server started

**Comment by kfranqueiro** [comment]
Sorry, looks like this was due to forgetting to update the webpack configs in #36. I'll send out a PR to fix it now.
