### ISSUE TITLE
[codelab] Repeated classname on demo.

### ISSUE THREAD

**Issue by scottcrossen** [material-components/material-components-web-codelabs#42]
Really simple mistake on the web walkthrough. I don't really mind it, but I'm just trying to be responsible by reporting:

the classname ".mdc-text-field" is repeated in the online walkthrough for one of the elements. [(section 4)](https://codelabs.developers.google.com/codelabs/mdc-101-web/#3)

![screenshot from 2018-06-07 23-14-36](https://user-images.githubusercontent.com/19987655/41140066-a89db0e8-6aa8-11e8-9f04-6f8d118f48a0.png)

**Comment by kfranqueiro** [comment]
Thanks for pointing this out! I just pushed an update to fix this.
