### ISSUE TITLE
[codelab] clicking on next lession takes to bottom of next lesson

### ISSUE THREAD

**Issue by lakshmanbasnet** [material-components/material-components-web-codelabs#44]
While clicking on next lesson at the bottom, I am in this [lesson](https://codelabs.developers.google.com/codelabs/mdc-101-web/#3), it takes me to bottom of next lesson instead of top beginning.

- I am using Mozilla Firefox.

**Comment by kfranqueiro** [comment]
Thanks for reporting this (and specifying browser, as this does seem to be a browser-specific issue).

This is an issue common to the codelabs platform, so I've reported it to the appropriate team. I'm going to close this since it's being tracked elsewhere instead.
