### ISSUE TITLE
[codelab] MDC-102 Invalid links on step 3 

### ISSUE THREAD

**Issue by steve-ross** [material-components/material-components-web-codelabs#45]
ON this page: https://codelabs.developers.google.com/codelabs/mdc-102-web/index.html?index=..%2F..%2Findex#2

The following links do not work:
![image](https://user-images.githubusercontent.com/297351/42339957-a26034de-805c-11e8-850f-a10c9600f691.png)

the links point to the following urls:
http://go/mdc-103-web

**Comment by bonniezhou** [comment]
Whoops, thanks for catching that! The link should be fixed now.
