### ISSUE TITLE
MDC-101 Typo in name of Node.js

### ISSUE THREAD

**Issue by PizzaFox** [material-components/material-components-web-codelabs#51]
> A recent version of **NodeJS** (which comes bundled with npm, a JavaScript package manager).

Emphasis mine. "NodeJS" should be spelled "Node.js" across many codelabs.

**Comment by kfranqueiro** [comment]
Thanks for pointing out the typo. I've fixed the prose and sent publish requests for all of the MDC Web codelabs to fix it.

**Comment by acdvorak** [comment]
Thanks for reporting this!
