### ISSUE TITLE
[mdc-101] 3. Add text fields >> Install the MDC Text Field and other copyedits

### ISSUE THREAD

**Issue by chalin** [material-components/material-components-web-codelabs#56]
1. Add `--save` option to `npm` commands on this an the next page; e.g.:

    ```
    npm install @material/textfield@0.35.0 --save
    ```

 2. In "Subelements mdc-text-field__input, mdc-text-field__label, and mdc-line-ripple" maybe `mdc-text-field__label` should be `mdc-floating-label` (which is what we see in the code excerpt just above the line).

cc @kwalrath

**Comment by kfranqueiro** [comment]
Thanks for reporting this issue!

RE #1, `--save` no longer exists in recent versions of npm (definitely not in 5 and up). Recent versions now have `--save-prod` as an equivalent, but this is already the default behavior.

RE #2, good catch! I've updated the prose and am pushing an update now.

**Comment by chalin** [comment]
Hi Kenneth. Oh right, it _is_ supposed to be the default behavior! But I'm using npm 6.x and it isn't saving by default. Strange. Also `--save` works just fine:

```console
> npm -v
6.2.0
> npm install @material/select@0.35.0 --save
+ @material/select@0.35.0
added 3 packages and audited 8969 packages in 5.095s
found 0 vulnerabilities
```

Wow that made me realize that my config setting was set to false for `save-prod`. (I wonder how that came to be. Anyhow, it's fixed.)

> I've updated the prose and am pushing an update now.

Great, thanks!
