### ISSUE TITLE
MDC-111 Web: 4. Update the select element issue

### ISSUE THREAD

**Issue by chalin** [material-components/material-components-web-codelabs#58]
Under [Update markup](https://codelabs.developers.google.com/codelabs/mdc-111-web/#3) the prose doesn't match the code excerpt with respect to the mdc label class to use:

> Just below the closing \</select> tag, replace the crane-label class with crane-select__label and **mdc-select__label**:
>
> \<label class="crane-select__label **mdc-floating-label**" for="crane-state-input">

Which one is correct?

cc @kwalrath

**Comment by chalin** [comment]
Btw, this part of the codelab doesn't work. I'm getting this error in the JS console:

```nocode
TypeError: Cannot read property 'addEventListener' of null
    at Object.registerInteractionHandler (index.js:84)
    at ACTIVATION_EVENT_TYPES.forEach.type (foundation.js:245)
    at Array.forEach (<anonymous>)
    at MDCRippleFoundation.registerRootHandlers_ (foundation.js:244)
    at MDCRippleFoundation.init (foundation.js:206)
    at new MDCComponent (component.js:51)
    at new MDCRipple (index.js:39)
    at MDCSelect.initRipple_ (index.js:88)
    at MDCSelect.initialize (index.js:78)
    at new MDCComponent (component.js:46)
```

(which is similar to what is reported here: https://github.com/material-components/material-components-web-components/issues/4)

**Comment by kfranqueiro** [comment]
RE your first question, `mdc-floating-label` is correct. Thanks for pointing this out; we'll get that fix published.

RE your second question, I suspect what's wrong is you didn't surround the original `select` with `<div class="crane-select mdc-select mdc-select--box">...</div>`. This is the final step mentioned in modifying the HTML.

**Comment by chalin** [comment]
> RE your second question, I suspect what's wrong is you didn't ...

Right, I was too eager, looking at the refreshed output before completing the necessary changes. It's working now, thanks!

**Comment by kfranqueiro** [comment]
Cool, no problem! Thanks again for the report.

**Comment by OtabekSadiridinov** [comment]
I've the same problem even tried with CDN. Try it out yourself too. You get that error.

**Comment by OtabekSadiridinov** [comment]
Just and HTML with CDN links. And you exactly get that error.
