### ISSUE TITLE
[codelab] Distracting tooltip anywhere I place the mouse

### ISSUE THREAD

**Issue by mdempsky** [material-components/material-components-web-codelabs#60]
https://codelabs.developers.google.com/codelabs/mdc-103-web/

Anytime I move the mouse, I get a "MDC-103 ..." tooltip popup. I like to move the mouse a lot while I'm reading, especially moving it over text I'm reading, so the tooltip is both very distracting and frequently obstructing the content I'm trying to read.

I'm using Chrome 70.0.3528.4 (Official Build) dev (64-bit) on Linux.

**Comment by kfranqueiro** [comment]
This is unfortunately an issue with the codelabs infrastructure itself, which is shared across all codelabs (not just MDC Web's). I've poked the internal issue for this again.
