### ISSUE TITLE
[codelab] Bug with import {MDCTextField} from '@material/textfield';  const username = new MDCTextField(document.querySelector('.username')); const password = new MDCTextField(document.querySelector('.password'));

### ISSUE THREAD

**Issue by lumeyisnotyou** [material-components/material-components-web-codelabs#80]
In brackets i get ERROR: Parsing error: The keyword 'import' is reserved   import {MDCTextField} from '@material/textfield';

**Comment by lumeyisnotyou** [comment]
anything with import does this

**Comment by moog16** [comment]
Try out [Atom](https://atom.io/) or [VSCode](https://code.visualstudio.com/). If you want to keep using brackets it seems like there are some issues regarding es6. You might need to turn on some preferences for it to be ES6 aware. This is not a code issue though. Checkout this [issue](https://github.com/adobe/brackets/issues/13720) for possible hints.
