### ISSUE TITLE
[codelab] GitHub 404 Error node-sass v4.9.0

### ISSUE THREAD

**Issue by bearlovesbob** [material-components/material-components-web-codelabs#81]
https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-67_binding.node does not exist anymore. I am wondering if there is a way to get that link updated so that I can install things properly to go through the tutorials that you have on the website.

**Comment by kfranqueiro** [comment]
Are you encountering an error when running `npm i` within the codelab directories? I'm under the impression that it should not be possible under ordinary circumstances for files to be deleted from npm, and I just tried in the MDC-101 starter directory using an empty npm cache and it worked.

**Comment by kfranqueiro** [comment]
Ah, I just realized it's looking at a different specific binding for my system, possibly dependent on OS version. It looks like only 4.10 and 4.11 have `-67`. We should look into updating. Thanks for pointing this out!

**Comment by bearlovesbob** [comment]
Thank you for working on this so quickly and for being able to find out the issue. What steps do I need to take to update what I have on my local system?

**Comment by kfranqueiro** [comment]
If you cloned the repository, you should be able to run `git pull` and then re-run `npm i` in each starter/complete folder. If you downloaded it as a zip, download it again from master.

**Comment by bearlovesbob** [comment]
Thank you again. Made it through all of the modules.

John Holman
