### ISSUE TITLE
Update codelabs to use MDC Web 1.0.0

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web-codelabs#83]
A few versions have been released since we last updated the codelabs, and especially since we decided to tag the first TypeScript version as 1.0.0, we should update the codelabs' dependencies and any affected code as necessary.

This does not necessarily include incorporating TypeScript into the codelabs, as that may require additional effort (but could also be seen as overwhelming to someone coming in completely new).

* [ ] mdc-101
* [ ] mdc-102
* [ ] mdc-103
* [ ] mdc-111
* [ ] mdc-112

**Comment by moog16** [comment]
[ ] remove node-sass
[ ] add dart-sass and fibers
[ ] update webpack config
