### ISSUE TITLE
[codelab] add buttons>add the html

### ISSUE THREAD

**Issue by wfd2018** [material-components/material-components-web-codelabs#84]
I suggest changing the instruction from:  In index.html, add the following below the `<div class="mdc-text-field password">` element:

to:  In index.html, add the following after the closing div tag `</div>`  of the div beginning with:  
     `<div class="mdc-text-field password">`

**Comment by kfranqueiro** [comment]
I've updated wording to make this more specific. Generally though, we distinguish "element" to refer to the entire tag + contents + closing tag. e.g., "inside the element" would be below the opening tag, whereas "after" or "below the element" would be below the closing tag.
