### ISSUE TITLE
The completed MDC-102 app

### ISSUE THREAD

**Issue by wfd2018** [material-components/material-components-web-codelabs#85]
It says:  The completed MDC-102 app is available in this directory: docs/codelabs/material-components-web-codelabs/mdc-102/complete 

it does not work in various browsers.  Please fix it.  Thanks

**Comment by kfranqueiro** [comment]
Can you be more specific as to the steps you performed and what doesn't work?

I suspect if anything you may have forgotten to run `npm install` before `npm start`. I noticed we had a sentence about this in MDC-101 but not 102, so I've updated that.

**Comment by kfranqueiro** [comment]
Given no further response, I'm going to close this issue. If my earlier response didn't resolve it, please provide more information to help us identify the issue. Thanks!
