### ISSUE TITLE
[codelab] Specified version of fibers is incompatible with current versions of Node

### ISSUE THREAD

**Issue by aholladay** [material-components/material-components-web-codelabs#89]
Specifically in the package.json file in mdc-101/starter. Attempting to `npm install` with node v12.1.0 will fail with an ambiguous error message and a log file 11,000 lines long.

The tutorial page here (https://codelabs.developers.google.com/codelabs/mdc-101-web/#0) DOES NOT SPECIFY which version to use, other than "a recent version," which is no longer true.

Please update your tutorial and/or packages.

**Comment by JPGrefaldo** [comment]
have the same issue

**Comment by abhiomkar** [comment]
I'm not able to reproduce this with below npm / node versions:

```
$ npm --version
6.5.0

$ node --version
v11.9.0
```

Maybe v12.1.0 node version has a breaking change that we're not aware of?

**Comment by abhiomkar** [comment]
This seems related https://github.com/laverdet/node-fibers/issues/409

Changing the fibers version to v4.0.0 seems to have fixed the issue.
