### ISSUE TITLE
Steps on publishing the code is missing

### ISSUE THREAD

**Issue by ggeldenhuis** [material-components/material-components-web-codelabs#97]
I am deep diving into web development so the knowledge is a bit sparse in places. I found the tutorials great but what is missing for me is how do I "convert" this into a published and functioning web page. Merely copying over the contents of mdc-103/complete directory to an apache server's /var/www/html does not work. The index.html displays but it is not rendered correctly. 

Thus some basic steps that details how to compile this into a functioning web page would be great.

**Comment by abhiomkar** [comment]
Please run `npx webpack` command (creates JS/CSS bundles) on `complete/` folder before deploying the folder to apache.

Hope this helps. Thanks!
