### ISSUE TITLE
[codelab] <App running on port 8081 not on 8080>

### ISSUE THREAD

**Issue by nagarjuna-immadi** [material-components/material-components-web-codelabs#99]
After executing "npm start" command, app running on 8081 port, not on 8080 as mentioned in article. https://codelabs.developers.google.com/codelabs/mdc-101-web/#1

![image](https://user-images.githubusercontent.com/5477552/69778312-d6ea4f00-11c9-11ea-880f-a4ea2a54bbc4.png)

![image](https://user-images.githubusercontent.com/5477552/69778324-e073b700-11c9-11ea-8beb-6b57926cea6d.png)

**Comment by pzaback** [comment]
Do you have something else running on port 8080? I've seen this before when working with Jupyter Notebooks where each instance increments the port used by one. Testing just now, running `npm start` the first time serves to port 8080 as expected for me, but when I invoke it a second time in a separate terminal session it serves to port 8081.

**Comment by abhiomkar** [comment]
It is likely that there is something else is running on port `:8080` which makes webpack-dev-server finds next available port.
